<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'foo' => 'get1',
  'Mikelooper\\ContainerSettings\\SettingsInterface' => 'get2',
  'settings' => 'get3',
  'subEntry1' => 'get4',
  'subEntry2' => 'get5',
  'subEntry3' => 'get6',
  'subEntry4' => 'get7',
  'subEntry5' => 'get8',
  'subEntry6' => 'get9',
  'subEntry7' => 'get10',
);

    protected function get1()
    {
        return 'bar';
    }

    protected function get2()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $container) {
        return new \Mikelooper\ContainerSettings\Settings($container->get('settings'));
    }, 'Mikelooper\\ContainerSettings\\SettingsInterface');
    }

    protected function get5()
    {
        return [
            'enabled' => true,
            'path' => '/code/tests/cache/container',
        ];
    }

    protected function get4()
    {
        return [
            'definitions' => '/code/tests/config/container.php',
            'cache' => $this->get5(),
        ];
    }

    protected function get7()
    {
        return [
            0 => 1,
        ];
    }

    protected function get8()
    {
        return [
            0 => 1,
            1 => '1',
        ];
    }

    protected function get10()
    {
        return [
            0 => 'value3',
        ];
    }

    protected function get9()
    {
        return [
            0 => 'value2',
            1 => $this->get10(),
        ];
    }

    protected function get6()
    {
        return [
            0 => NULL,
            1 => 1,
            2 => $this->get7(),
            3 => $this->get8(),
            'setting1' => NULL,
            'setting2' => 1,
            'setting3' => 1.0,
            'setting4' => 'value1',
            'setting5' => $this->get9(),
        ];
    }

    protected function get3()
    {
        return [
            'root' => '/code/tests',
            'config' => '/code/tests/config/',
            'cache' => '/code/tests/cache/',
            'container' => $this->get4(),
            'test' => $this->get6(),
        ];
    }

}
